-- CREATE DATABASE
CREATE DATABASE IF NOT EXISTS ALX_BOOK_STORE;
USE ALX_BOOK_STORE;

CREATE TABLE AUTHORS (
    AUTHOR_ID INT AUTO_INCREMENT,
    AUTHOR_NAME VARCHAR(215),
    PRIMARY KEY (AUTHOR_ID)
);
CREATE TABLE BOOKS (
    BOOK_ID INT AUTO_INCREMENT,
    TITLE VARCHAR(130),
    AUTHOR_ID INT,
    PRICE DOUBLE,
    PUBLICATION_DATE DATE,
    PRIMARY KEY (BOOK_ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
);
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INT AUTO_INCREMENT,
    CUSTOMER_NAME VARCHAR(215),
    EMAIL VARCHAR(215),
    ADDRESS TEXT,
    PRIMARY KEY (CUSTOMER_ID)
);
CREATE TABLE ORDERS (
    ORDER_ID INT AUTO_INCREMENT,
    CUSTOMER_ID INT,
    ORDER_DATE DATE,
    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);
CREATE TABLE ORDER_DETAILS (
    ORDERDETAILID INT AUTO_INCREMENT,
    ORDER_ID INT,
    BOOK_ID INT,
    QUANTITY DOUBLE,
    PRIMARY KEY (ORDERDETAILID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID)
);
